#### Imports

In [2]:
import numpy as np
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt

#### Reading in the Data

In [3]:
plays = pd.read_csv('NFL_Play_by_Play_2009-2018_(v5).csv')

/var/folders/c7/1qq7lbrd6p50qcnbj7skxq4c0000gn/T/ipykernel_63591/3835304158.py:1: DtypeWarning: Columns (42,166,167,168,169,174,175,178,179,182,183,188,189,190,191,194,195,203,204,205,218,219,220,231,232,233,238,240,241,249) have mixed types. Specify dtype option on import or set low_memory=False.
  plays = pd.read_csv('NFL_Play_by_Play_2009-2018_(v5).csv')

In [4]:
# looking at breakdowns of the columns by dtype
plays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 449371 entries, 0 to 449370
Columns: 255 entries, play_id to defensive_extra_point_conv
dtypes: float64(135), int64(18), object(102)
memory usage: 874.2+ MB

In [5]:
# Looking at 5 random plays
plays.sample(5)

,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,...,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
387146,115,2017111208,LA,HOU,HOU,away,LA,HOU,66.0,2017-11-12,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
96235,1584,2011092502,BUF,NE,NE,away,BUF,BUF,47.0,2011-09-25,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
23319,973,2009111504,PIT,CIN,CIN,away,PIT,CIN,57.0,2009-11-15,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
143916,483,2012093003,DET,MIN,DET,home,MIN,DET,57.0,2012-09-30,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
291974,3993,2015110200,CAR,IND,IND,away,CAR,CAR,48.0,2015-11-02,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0

### Filtering for the plays with a valid play type

In [6]:
# count of plays with no play type
plays['play_type'].isnull().value_counts()

play_type
False    436497
True      12874
Name: count, dtype: int64

In [7]:
#filtering for the valid plays
completed_plays = plays[plays['play_type'].notna()]

In [10]:
# finding a few descriptive statistics 
completed_plays.info()

<class 'pandas.core.frame.DataFrame'>
Index: 436497 entries, 0 to 449369
Columns: 255 entries, play_id to defensive_extra_point_conv
dtypes: float64(135), int64(18), object(102)
memory usage: 852.5+ MB

#### Null Values Exploration

In [11]:
# finding the columns with the highest number of null values
completed_plays.isnull().sum().sort_values(ascending=False).head(30)

assist_tackle_4_team                    436497
lateral_sack_player_id                  436497
lateral_sack_player_name                436497
assist_tackle_4_player_id               436497
assist_tackle_4_player_name             436497
assist_tackle_3_player_id               436494
assist_tackle_3_player_name             436494
assist_tackle_3_team                    436494
tackle_for_loss_2_player_name           436489
tackle_for_loss_2_player_id             436489
lateral_rusher_player_id                436480
lateral_rusher_player_name              436480
lateral_punt_returner_player_name       436474
lateral_punt_returner_player_id         436474
lateral_interception_player_id          436474
lateral_interception_player_name        436474
forced_fumble_player_2_player_name      436465
forced_fumble_player_2_team             436464
forced_fumble_player_2_player_id        436464
fumbled_2_player_id                     436459
lateral_kickoff_returner_player_id      436459
fumbled_2_player_name                   436459
lateral_kickoff_returner_player_name    436459
fumbled_2_team                          436459
fumble_recovery_2_player_name           436451
fumble_recovery_2_player_id             436450
fumble_recovery_2_yards                 436450
fumble_recovery_2_team                  436450
own_kickoff_recovery_player_name        436403
own_kickoff_recovery_player_id          436403
dtype: int64

In [12]:
# dropping the columns with mostly null values
completed_plays_v2 = completed_plays.dropna(axis = 1, thresh=10000)

In [13]:
completed_plays_v2

,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,...,penalty_team,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,46,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,2009-09-10,...,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
1,68,2009091000,PIT,TEN,PIT,home,TEN,PIT,58.0,2009-09-10,...,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
2,92,2009091000,PIT,TEN,PIT,home,TEN,PIT,53.0,2009-09-10,...,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
3,113,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
4,139,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449365,4027,2018121700,CAR,NO,CAR,home,NO,CAR,66.0,2018-12-17,...,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
449366,4059,2018121700,CAR,NO,CAR,home,NO,CAR,66.0,2018-12-17,...,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
449367,4081,2018121700,CAR,NO,CAR,home,NO,CAR,66.0,2018-12-17,...,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
449368,4106,2018121700,CAR,NO,CAR,home,NO,CAR,61.0,2018-12-17,...,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
449369,4128,2018121700,CAR,NO,NO,away,CAR,CAR,39.0,2018-12-17,...,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0

In [15]:
completed_plays_v2["play_type"]

0          kickoff
1             pass
2              run
3             pass
4             punt
            ...
449365    qb_spike
449366        pass
449367        pass
449368        pass
449369    qb_kneel
Name: play_type, Length: 436497, dtype: object

#### Feature Engineering with Domain Knowledge

In [14]:
# finding the columns with player names in it to filter out - not relevant
player_cols = [x for x in completed_plays_v2.columns if 'player' in x]   

# finding the columns with 'id' in it - not helpful
id_cols = [x for x in completed_plays_v2.columns if 'id' in x]  

# finding the columns with 'posteam' in it - all repetitive
posteam_cols = [x for x in completed_plays_v2.columns if 'posteam' in x] 

# finding the columns with 'lateral' in it - not helpful
lateral_cols = [x for x in completed_plays_v2.columns if 'lateral' in x]

In [16]:
# making the new df getting rid of unnecessary data
completed_plays_v3 = completed_plays_v2.drop(columns = player_cols + id_cols + posteam_cols + lateral_cols)

In [17]:
# looking at descriptive statistics
completed_plays_v3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 436497 entries, 0 to 449369
Columns: 157 entries, home_team to defensive_extra_point_conv
dtypes: float64(119), int64(16), object(22)
memory usage: 526.2+ MB

In [18]:
completed_plays_v3

,home_team,away_team,defteam,yardline_100,game_date,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,...,return_team,return_yards,penalty_team,penalty_yards,replay_or_challenge,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,PIT,TEN,TEN,30.0,2009-09-10,900.0,1800.0,3600.0,Half1,0,...,PIT,39.0,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
1,PIT,TEN,TEN,58.0,2009-09-10,893.0,1793.0,3593.0,Half1,0,...,NaN,0.0,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
2,PIT,TEN,TEN,53.0,2009-09-10,856.0,1756.0,3556.0,Half1,0,...,NaN,0.0,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
3,PIT,TEN,TEN,56.0,2009-09-10,815.0,1715.0,3515.0,Half1,0,...,NaN,0.0,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
4,PIT,TEN,TEN,56.0,2009-09-10,807.0,1707.0,3507.0,Half1,0,...,NaN,0.0,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449365,CAR,NO,NO,66.0,2018-12-17,64.0,64.0,64.0,Half2,0,...,NaN,0.0,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
449366,CAR,NO,NO,66.0,2018-12-17,63.0,63.0,63.0,Half2,0,...,NaN,0.0,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
449367,CAR,NO,NO,66.0,2018-12-17,58.0,58.0,58.0,Half2,0,...,NaN,0.0,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
449368,CAR,NO,NO,61.0,2018-12-17,38.0,38.0,38.0,Half2,0,...,NaN,0.0,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0
449369,CAR,NO,CAR,39.0,2018-12-17,35.0,35.0,35.0,Half2,0,...,NaN,0.0,NaN,NaN,0,NaN,0.0,0.0,0.0,0.0

In [24]:
def classify_play_type(x):
    if x == "pass":
        return 1
    else:
        return 0

In [ ]:
completed_plays_v3 = completed_plays_v3.query("play_type == 'pass' or play_type == run")

In [25]:
completed_plays_v3["play_type"] = completed_plays_v3["play_type"].apply(classify_play_type)

/var/folders/c7/1qq7lbrd6p50qcnbj7skxq4c0000gn/T/ipykernel_63591/3401629442.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_plays_v3["play_type"] = completed_plays_v3["play_type"].apply(classify_play_type)

In [26]:
completed_plays_v3["play_type"]

1         1
2         0
3         1
5         0
6         1
         ..
449363    1
449364    1
449366    1
449367    1
449368    1
Name: play_type, Length: 319369, dtype: int64

#### Filtering Out the Object Columns for Additional Analysis

In [27]:
# getting rid of object columns - descriptions and team names not always helpful
completed_plays_v4 = completed_plays_v3.drop(columns=completed_plays_v3.select_dtypes(include=['object']).columns)

In [28]:
completed_plays_v4

,yardline_100,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,quarter_end,drive,sp,qtr,down,goal_to_go,...,fumble,complete_pass,assist_tackle,return_yards,penalty_yards,replay_or_challenge,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
1,58.0,893.0,1793.0,3593.0,0,1,0,1,1.0,0.0,...,0.0,1.0,0.0,0.0,NaN,0,0.0,0.0,0.0,0.0
2,53.0,856.0,1756.0,3556.0,0,1,0,1,2.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0,0.0,0.0,0.0,0.0
3,56.0,815.0,1715.0,3515.0,0,1,0,1,3.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0,0.0,0.0,0.0,0.0
5,98.0,796.0,1696.0,3496.0,0,2,0,1,1.0,0.0,...,0.0,0.0,1.0,0.0,NaN,0,0.0,0.0,0.0,0.0
6,98.0,760.0,1660.0,3460.0,0,2,0,1,2.0,0.0,...,0.0,1.0,0.0,0.0,NaN,0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449363,71.0,82.0,82.0,82.0,0,20,0,4,2.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0,0.0,0.0,0.0,0.0
449364,71.0,77.0,77.0,77.0,0,20,0,4,3.0,0.0,...,0.0,1.0,0.0,0.0,NaN,0,0.0,0.0,0.0,0.0
449366,66.0,63.0,63.0,63.0,0,20,0,4,2.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0,0.0,0.0,0.0,0.0
449367,66.0,58.0,58.0,58.0,0,20,0,4,3.0,0.0,...,0.0,1.0,0.0,0.0,NaN,0,0.0,0.0,0.0,0.0
449368,61.0,38.0,38.0,38.0,0,20,0,4,4.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0,0.0,0.0,0.0,0.0

#### PCA for Dimensionality Reduction

In [30]:
# fill all the null values with 0 values for PCA
completed_plays_v4 = completed_plays_v4.fillna(0).reset_index().drop('index', axis=1)

In [31]:
completed_plays_v4

,yardline_100,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,quarter_end,drive,sp,qtr,down,goal_to_go,...,fumble,complete_pass,assist_tackle,return_yards,penalty_yards,replay_or_challenge,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,58.0,893.0,1793.0,3593.0,0,1,0,1,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
1,53.0,856.0,1756.0,3556.0,0,1,0,1,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
2,56.0,815.0,1715.0,3515.0,0,1,0,1,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
3,98.0,796.0,1696.0,3496.0,0,2,0,1,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0,0.0,0.0,0.0,0.0
4,98.0,760.0,1660.0,3460.0,0,2,0,1,2.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319364,71.0,82.0,82.0,82.0,0,20,0,4,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
319365,71.0,77.0,77.0,77.0,0,20,0,4,3.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
319366,66.0,63.0,63.0,63.0,0,20,0,4,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
319367,66.0,58.0,58.0,58.0,0,20,0,4,3.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
319368,61.0,38.0,38.0,38.0,0,20,0,4,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0

In [32]:
completed_plays_v4.shape

(319369, 136)

In [33]:
from sklearn.decomposition import PCA

# Fit PCA and get the explained variance
pca = PCA(n_components=3)
pca.fit(completed_plays_v4)
print("Explained variance ratio:", pca.explained_variance_ratio_.round(2))

Explained variance ratio: [0.82 0.15 0.03]

In [34]:
loads = pca.transform(completed_plays_v4)

In [35]:
loads = pd.DataFrame(loads, columns=["PC1", "PC2", "PC3"])
loads

                PC1         PC2         PC3
0       2085.346919 -393.322974 -153.988402
1       2035.623481 -360.113164 -130.900189
2       1980.530480 -323.309756 -105.318776
3       1955.081945 -306.474579  -93.646573
4       1906.702242 -274.156278  -71.177440
...             ...         ...         ...
319364 -1839.696207  266.475571  112.730842
319365 -1846.411351  270.954912  115.844913
319366 -1865.234946  283.544464  124.600636
319367 -1871.948992  288.023649  127.713734
319368 -1898.834906  305.990692  140.206613

[319369 rows x 3 columns]

In [21]:
# creating a df to associate each column with its respective principal component
loadings = pd.DataFrame(pca.components_.T, columns=[f"PC{i+1}" for i in range(pca.n_components_)], index=completed_plays_v4.columns)

In [22]:
# creating separate series of each PC sorted by importance
pc_1_vals = loadings['PC1'].abs().sort_values(ascending=False)
pc_2_vals = loadings['PC2'].abs().sort_values(ascending=False)
pc_3_vals = loadings['PC3'].abs().sort_values(ascending=False)

In [33]:
loadings

                                        PC1           PC2           PC3
yardline_100                   1.647451e-03 -3.566049e-03 -3.178956e-03
quarter_seconds_remaining      9.584628e-02 -3.415886e-01 -9.349270e-01
half_seconds_remaining         3.205601e-01 -8.786218e-01  3.539056e-01
game_seconds_remaining         9.422683e-01  3.335823e-01 -2.528389e-02
quarter_end                   -7.669488e-35 -1.576295e-34 -1.072188e-33
...                                     ...           ...           ...
replay_or_challenge           -3.961645e-07  1.403531e-06  1.060741e-06
defensive_two_point_attempt   -2.081514e-08  7.182833e-09 -1.136915e-07
defensive_two_point_conv      -8.331545e-09  8.091918e-09 -2.864184e-09
defensive_extra_point_attempt  0.000000e+00 -0.000000e+00 -0.000000e+00
defensive_extra_point_conv     0.000000e+00 -0.000000e+00 -0.000000e+00

[135 rows x 3 columns]

In [36]:
combined_data = completed_plays_v4.join(loads)

In [37]:
combined_data

,yardline_100,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,quarter_end,drive,sp,qtr,down,goal_to_go,...,return_yards,penalty_yards,replay_or_challenge,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv,PC1,PC2,PC3
0,58.0,893.0,1793.0,3593.0,0,1,0,1,1.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,2085.346919,-393.322974,-153.988402
1,53.0,856.0,1756.0,3556.0,0,1,0,1,2.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,2035.623481,-360.113164,-130.900189
2,56.0,815.0,1715.0,3515.0,0,1,0,1,3.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,1980.530480,-323.309756,-105.318776
3,98.0,796.0,1696.0,3496.0,0,2,0,1,1.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,1955.081945,-306.474579,-93.646573
4,98.0,760.0,1660.0,3460.0,0,2,0,1,2.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,1906.702242,-274.156278,-71.177440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319364,71.0,82.0,82.0,82.0,0,20,0,4,2.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,-1839.696207,266.475571,112.730842
319365,71.0,77.0,77.0,77.0,0,20,0,4,3.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,-1846.411351,270.954912,115.844913
319366,66.0,63.0,63.0,63.0,0,20,0,4,2.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,-1865.234946,283.544464,124.600636
319367,66.0,58.0,58.0,58.0,0,20,0,4,3.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,-1871.948992,288.023649,127.713734
319368,61.0,38.0,38.0,38.0,0,20,0,4,4.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,-1898.834906,305.990692,140.206613

In [38]:
combined_data.to_csv("cleaned_data.csv")